# Generated by Django 3.0.4 on 2020-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('p_email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('u_email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.NullBooleanField(default=0)),
            ],
        ),
    ]
