# Generated by Django 3.0.4 on 2020-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
