# Generated by Django 3.0.4 on 2020-05-19 05:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('backend_app', '0002_roledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDetails',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('verify_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
                ('otp_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.UserRole')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='RoleDetail',
        ),
    ]
