# Generated by Django 3.0.4 on 2020-05-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_auto_20200519_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledetails',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
