# Generated by Django 3.0.4 on 2020-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_roledetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
            ],
        ),
    ]
