# Generated by Django 3.0.4 on 2020-05-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetails',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.UserRole'),
        ),
    ]
