# Generated by Django 3.0.4 on 2020-05-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_auto_20200527_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetails',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.UserRole'),
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('cover_photo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('photo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Categories')),
            ],
        ),
    ]
