# Generated by Django 3.0.4 on 2020-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_auto_20200528_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='p_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
