# Generated by Django 3.0.4 on 2020-05-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_auto_20200528_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
