# Generated by Django 3.0.4 on 2020-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_auto_20200608_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycart',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
