# Generated by Django 3.0.4 on 2020-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_invoicetable_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetable',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
